classdef ConnectomeGenePairDataSet
    properties
        % Core data
        SourceIDs (:,1) {mustBeInteger}          % [#Connection,1] Source region index
        TargetIDs (:,1) {mustBeInteger}          % [#Connection,1] Target region index
        SourceExpressions (:,:) {mustBeNumeric}  % [#Connection,#Expression] Expression values of source
        TargetExpressions (:,:) {mustBeNumeric}  % [#Connection,#Expression] Expression values of target
        DomainDefineMask (:,:) logical           % [#Region,#Region] Region pairs of interest 
        % Metadata
        GenerationInfo      % meta information (struct)
        Description         % explanatory text 
    end

    methods
        function obj = ConnectomeGenePairDataSet( ...
                SourceIDs, TargetIDs, SourceExpressions, TargetExpressions, domainDefineMask, ...
                options)

            arguments
                SourceIDs (:,1) double
                TargetIDs (:,1) double
                SourceExpressions (:,:) double
                TargetExpressions (:,:) double
                domainDefineMask (:,:) logical
                options.GenerationInfo struct = struct();
                options.Description string = "";
            end

            obj.SourceIDs = SourceIDs;
            obj.TargetIDs = TargetIDs;
            obj.SourceExpressions = SourceExpressions;
            obj.TargetExpressions = TargetExpressions;
            obj.DomainDefineMask = domainDefineMask;
            obj.GenerationInfo = options.GenerationInfo;
            obj.Description = options.Description;

            obj = obj.validateSizes();
        end

        function obj = validateSizes(obj)
            % Check the size consistency of data
            N = numel(obj.SourceIDs);
            if numel(obj.TargetIDs) ~= N
                error('SourceIDs and TargetIDs must have the same length.');
            end
            if size(obj.SourceExpressions,1) ~= N
                error('Row count of SourceExpressions must match number of pairs.');
            end
            if size(obj.TargetExpressions,1) ~= N
                error('Row count of TargetExpressions must match number of pairs.');
            end
        end

        function summary(obj)
            % display information
            fprintf('ConnectomeGenePairDataSet with %d pairs.\n', numel(obj.SourceIDs));
            if isfield(obj.GenerationInfo, 'FactoryID')
                fprintf('Generated by Factory: %s\n', obj.GenerationInfo.FactoryID);
            end
            if ~isempty(obj.Description)
                fprintf('Description: %s\n', obj.Description);
            end
        end
    end
end